pragma Singleton
import QtQuick 2.3

QtObject {
    readonly property var commandTable: {
        0:   [ "indigo",     0, "" ],
        101: [ "indigo",     1, qsTr("Text"), qsTr("Show Text") ],
        401: [ "indigo",     2, qsTr("Text") ],
        102: [ "indigo",     1, qsTr("Show Choices") ],
        103: [ "indigo",     1, qsTr("Input Number") ],
        402: [ "indigo",     2, "" ],
        403: [ "indigo",     0, qsTr("When Cancel") ],
        404: [ "indigo",     0, qsTr("End", "Branch End") ],
        104: [ "indigo",     1, qsTr("Select Item") ],
        105: [ "indigo",     1, qsTr("Text(S)"), qsTr("Show Scrolling Text") ],
        405: [ "indigo",     2, qsTr("Text(S)") ],
        108: [ "green",      1, qsTr("Comment") ],
        408: [ "green",      2, qsTr("Comment") ],
        111: [ "blue",       1, qsTr("If"), qsTr("Conditional Branch") ],
        411: [ "blue",       0, qsTr("Else") ],
        412: [ "blue",       0, qsTr("End", "Branch End") ],
        112: [ "blue",       0, qsTr("Loop") ],
        413: [ "blue",       0, qsTr("Repeat Above") ],
        113: [ "blue",       0, qsTr("Break Loop") ],
        114: [ "blue",       0, qsTr("Continue Loop") ],
        115: [ "blue",       0, qsTr("Exit Event Processing") ],
        117: [ "blue",       1, qsTr("Common Event") ],
        118: [ "blue",       1, qsTr("Label") ],
        119: [ "blue",       1, qsTr("Jump to Label") ],
        121: [ "red",        1, qsTr("Control Switches") ],
        122: [ "red",        1, qsTr("Control Variables") ],
        357: [ "gray",       0, qsTr("Control Self Variable")],
        123: [ "red",        1, qsTr("Control Self Switch") ],
        124: [ "red",        1, qsTr("Control Timer") ],
        125: [ "darkorange", 1, qsTr("Change Gold") ],
        126: [ "darkorange", 1, qsTr("Change Items") ],
        127: [ "darkorange", 1, qsTr("Change Weapons") ],
        128: [ "darkorange", 1, qsTr("Change Armors") ],
        129: [ "darkorange", 1, qsTr("Change Party Member") ],
        132: [ "magenta",    1, qsTr("Change Battle BGM") ],
        133: [ "magenta",    1, qsTr("Change Victory ME") ],
        134: [ "magenta",    1, qsTr("Change Save Access") ],
        135: [ "magenta",    1, qsTr("Change Menu Access") ],
        136: [ "magenta",    1, qsTr("Change Encounter") ],
        137: [ "magenta",    1, qsTr("Change Formation Access") ],
        138: [ "magenta",    1, qsTr("Change Window Color") ],
        139: [ "magenta",    1, qsTr("Change Defeat ME") ],
        140: [ "magenta",    1, qsTr("Change Vehicle BGM") ],
        201: [ "maroon",     1, qsTr("Transfer Player") ],
        202: [ "maroon",     1, qsTr("Set Vehicle Location") ],
        203: [ "maroon",     1, qsTr("Set Event Location") ],
        204: [ "maroon",     1, qsTr("Scroll Map") ],
        205: [ "maroon",     1, qsTr("Set Movement Route") ],
        505: [ "maroon",     2, qsTr("Set Movement Route") ],
        206: [ "maroon",     0, qsTr("Get on/off Vehicle") ],
        211: [ "maroon",     1, qsTr("Change Transparency") ],
        216: [ "maroon",     1, qsTr("Change Player Followers") ],
        217: [ "maroon",     0, qsTr("Gather Followers") ],
        212: [ "maroon",     1, qsTr("Show Animation") ],
        213: [ "maroon",     1, qsTr("Show Balloon Icon") ],
        214: [ "maroon",     0, qsTr("Erase Event") ],
        221: [ "olive",      0, qsTr("Fadeout Screen") ],
        222: [ "olive",      0, qsTr("Fadein Screen") ],
        223: [ "olive",      1, qsTr("Tint Screen") ],
        224: [ "olive",      1, qsTr("Flash Screen") ],
        225: [ "olive",      1, qsTr("Shake Screen") ],
        230: [ "crimson",    1, qsTr("Wait") ],
        231: [ "purple",     1, qsTr("Show Picture") ],
        232: [ "purple",     1, qsTr("Move Picture") ],
        233: [ "purple",     1, qsTr("Rotate Picture") ],
        234: [ "purple",     1, qsTr("Tint Picture") ],
        235: [ "purple",     1, qsTr("Erase Picture") ],
        236: [ "olive",      1, qsTr("Set Weather Effect") ],
        241: [ "teal",       1, qsTr("Play BGM") ],
        242: [ "teal",       1, qsTr("Fadeout BGM") ],
        243: [ "teal",       0, qsTr("Save BGM") ],
        244: [ "teal",       0, qsTr("Replay BGM") ],
        245: [ "teal",       1, qsTr("Play BGS") ],
        246: [ "teal",       1, qsTr("Fadeout BGS") ],
        249: [ "teal",       1, qsTr("Play ME") ],
        250: [ "teal",       1, qsTr("Play SE") ],
        251: [ "teal",       0, qsTr("Stop SE") ],
        261: [ "teal",       1, qsTr("Play Movie") ],
        281: [ "deeppink",   1, qsTr("Change Map Name Display") ],
        282: [ "deeppink",   1, qsTr("Change Tileset") ],
        283: [ "deeppink",   1, qsTr("Change Battle Back") ],
        284: [ "deeppink",   1, qsTr("Change Parallax") ],
        285: [ "deeppink",   1, qsTr("Get Location Info") ],
        301: [ "dodgerblue", 1, qsTr("Battle Processing") ],
        601: [ "dodgerblue", 0, qsTr("If Win") ],
        602: [ "dodgerblue", 0, qsTr("If Escape") ],
        603: [ "dodgerblue", 0, qsTr("If Lose") ],
        604: [ "dodgerblue", 0, qsTr("End", "Branch End") ],
        302: [ "dodgerblue", 1, qsTr("Shop Processing") ],
        605: [ "dodgerblue", 2, qsTr("Shop Processing") ],
        303: [ "dodgerblue", 1, qsTr("Name Input Processing") ],
        311: [ "darkorange", 1, qsTr("Change HP") ],
        312: [ "darkorange", 1, qsTr("Change MP") ],
        326: [ "darkorange", 1, qsTr("Change TP") ],
        313: [ "darkorange", 1, qsTr("Change State") ],
        314: [ "darkorange", 1, qsTr("Recover All") ],
        315: [ "darkorange", 1, qsTr("Change EXP") ],
        316: [ "darkorange", 1, qsTr("Change Level") ],
        317: [ "darkorange", 1, qsTr("Change Parameter") ],
        318: [ "darkorange", 1, qsTr("Change Skill") ],
        319: [ "darkorange", 1, qsTr("Change Equipment") ],
        320: [ "darkorange", 1, qsTr("Change Name") ],
        321: [ "darkorange", 1, qsTr("Change Class") ],
        322: [ "magenta",    1, qsTr("Change Actor Images") ],
        323: [ "magenta",    1, qsTr("Change Vehicle Image") ],
        324: [ "darkorange", 1, qsTr("Change Nickname") ],
        325: [ "darkorange", 1, qsTr("Change Profile") ],
        331: [ "darkviolet", 1, qsTr("Change Enemy HP") ],
        332: [ "darkviolet", 1, qsTr("Change Enemy MP") ],
        342: [ "darkviolet", 1, qsTr("Change Enemy TP") ],
        333: [ "darkviolet", 1, qsTr("Change Enemy State") ],
        334: [ "darkviolet", 1, qsTr("Enemy Recover All") ],
        335: [ "darkviolet", 1, qsTr("Enemy Appear") ],
        336: [ "darkviolet", 1, qsTr("Enemy Transform") ],
        337: [ "darkviolet", 1, qsTr("Show Battle Animation") ],
        339: [ "darkviolet", 1, qsTr("Force Action") ],
        340: [ "darkviolet", 0, qsTr("Abort Battle") ],
        351: [ "dodgerblue", 0, qsTr("Open Menu Screen") ],
        352: [ "dodgerblue", 0, qsTr("Open Save Screen") ],
        353: [ "dodgerblue", 0, qsTr("Game Over") ],
        354: [ "dodgerblue", 0, qsTr("Return to Title Screen") ],
        355: [ "indigo",     1, qsTr("Script") ],
        655: [ "indigo",     2, qsTr("Script") ],
        356: [ "indigo",     1, qsTr("Plugin Command") ],
        999: [ "gray",       0, qsTr("Undefined Command") ]
    }

    readonly property var hintTable: {
        101: qsTr("Opens the message window and displays text."),
        102: qsTr("Displays a list of choices and branches handling."),
        103: qsTr("Enters a natural number and stores it in a variable."),
        104: qsTr("Selects an item possessed by the party and stores its item ID in a variable."),
        105: qsTr("Displays text that scrolls from the bottom of the screen to the top."),
        121: qsTr("Turns a switch ON/OFF."),
        122: qsTr("Changes the numeric value stored in the variable."),
        123: qsTr("Turns a self switch ON/OFF. Used only on the map screen."),
        124: qsTr("Starts or stops the timer."),
        111: qsTr("Creates a portion to be run only when specific conditions are met."),
        112: qsTr("Creates a portion to be run repeatedly."),
        113: qsTr("Escapes the innermost loop."),
        115: qsTr("Ends running events."),
        117: qsTr("Calls up a common event. When the called event is complete, moves onto the next command."),
        118: qsTr("Sets the label name for jump."),
        119: qsTr("Moves to the specified label name. Only valid within this event list."),
        108: qsTr("Sets the comments displayed in the list. Has no effect in the game."),
        125: qsTr("Changes the amount of money in the party's inventory."),
        126: qsTr("Changes the item in the party's inventory."),
        127: qsTr("Changes the weapon in the party's inventory."),
        128: qsTr("Changes the armor in the party's inventory."),
        129: qsTr("Changes the actor in the party."),
        311: qsTr("Changes the HP of the actor."),
        312: qsTr("Changes the MP of the actor."),
        326: qsTr("Changes the TP of the actor."),
        313: qsTr("Changes the state of the actor."),
        314: qsTr("Clears all states and fully recovers HP and MP."),
        315: qsTr("Changes the EXP of the actor."),
        316: qsTr("Changes the level of the actor."),
        317: qsTr("Changes the parameter of the actor."),
        318: qsTr("Changes the skill of the actor."),
        319: qsTr("Changes the equipment of the actor."),
        320: qsTr("Changes the name of the actor."),
        321: qsTr("Changes the class of the actor."),
        324: qsTr("Changes the nickname of the actor."),
        325: qsTr("Changes the profile of the actor."),
        201: qsTr("Changes the current location of the player. Used only on the map screen."),
        202: qsTr("Changes the current location of the specified vehicle."),
        203: qsTr("Changes the current location of the specified event. Cannot move the event to a different map."),
        204: qsTr("Scrolls the map without changing the player's location. Used only on the map screen."),
        205: qsTr("Forces the player or event to move. If a route already exists, it will be overwritten."),
        206: qsTr("Puts the player on a vehicle. If the player is already on a vehicle, puts him on the ground."),
        211: qsTr("Changes whether to show or hide the player on the map."),
        216: qsTr("Changes whether to show or hide the party members that follow behind the player."),
        217: qsTr("Moves all party members to the same position as the lead character."),
        212: qsTr("Displays the specified animation to the character on the map."),
        213: qsTr("Displays the specified balloon icon above the character's head."),
        214: qsTr("Temporarily removes the current event on the map. If the player moves off of the map and returns, the event will reappear."),
        221: qsTr("Fades out the entire screen."),
        222: qsTr("Fades in the entire screen."),
        223: qsTr("Changes the color tone of the entire screen. Also affects the battle screen."),
        224: qsTr("Temporarily fill the entire screen with a color, then gradually revert to the original color."),
        225: qsTr("Shakes the entire screen from side to side."),
        230: qsTr("Waits for a certain period of time."),
        231: qsTr("Displays the specified picture on top of the screen."),
        232: qsTr("Changes the properties of the picture."),
        233: qsTr("Changes the rotation speed of the picture."),
        234: qsTr("Changes the color tone of the picture."),
        235: qsTr("Removes the picture."),
        236: qsTr("Changes the weather effect such as rain and snow."),
        241: qsTr("Plays the specified BGM."),
        242: qsTr("Fades out the current BGM."),
        243: qsTr("Saves the current BGM."),
        244: qsTr("Replays the saved BGM."),
        245: qsTr("Plays the specified BGS."),
        246: qsTr("Fades out the current BGS."),
        249: qsTr("Plays the specified ME."),
        250: qsTr("Plays the specified SE."),
        251: qsTr("Stop all the SE."),
        301: qsTr("Starts a battle."),
        302: qsTr("Calls up the shop screen."),
        303: qsTr("Calls up the name input screen."),
        351: qsTr("Calls up the menu screen."),
        352: qsTr("Calls up the save screen."),
        353: qsTr("Forces Game Over."),
        354: qsTr("Returns to the title screen."),
        132: qsTr("Changes the BGM to be played during a battle."),
        133: qsTr("Changes the ME to be played at winning a battle."),
        134: qsTr("Enables or disables the saving of game data."),
        135: qsTr("Enables or disables menu screen calls."),
        136: qsTr("Enables or disables random encounters."),
        137: qsTr("Enables or disables the formation command."),
        138: qsTr("Changes the window background color."),
        139: qsTr("Changes the ME to be played at losing a battle."),
        140: qsTr("Changes the BGM to be played while riding in a vehicle."),
        322: qsTr("Changes the image of the actor."),
        323: qsTr("Changes the image of the specified vehicle."),
        261: qsTr("Plays the specified movie. Event processing is stopped until the movie ends."),
        281: qsTr("Changes whether to display the map name when changing the current map."),
        282: qsTr("Changes the tileset used by the current map temporarily."),
        283: qsTr("Changes the battle background associated with the current map temporarily."),
        284: qsTr("Changes the parallax background associated with the current map temporarily."),
        285: qsTr("Gets information related to specific coordinates on the current map."),
        331: qsTr("Changes the HP of the enemy."),
        332: qsTr("Changes the MP of the enemy."),
        342: qsTr("Changes the TP of the enemy."),
        333: qsTr("Changes the state of the enemy."),
        334: qsTr("Clears all states and fully recovers the HP and MP of the enemy."),
        335: qsTr("Makes the enemy who has the [Appear Halfway] option to appear."),
        336: qsTr("Transforms the enemy. HP and MP will not be changed."),
        337: qsTr("Displays the specified animation on the battle screen."),
        339: qsTr("Forces the specified action."),
        340: qsTr("Exits the battle."),
        355: qsTr("Evaluates text as JavaScript."),
        356: qsTr("Send a command to a plugin.")
    }

    function get(code) {
        return commandTable[code] || commandTable[999];
    }

    function color(code) {
        return get(code)[0];
    }

    function flag(code) {
        return get(code)[1];
    }

    function shortName(code) {
        return get(code)[2];
    }

    function longName(code) {
        return get(code)[3] || shortName(code);
    }

    function buttonText(code) {
        return '<font color=' + color(code) + '>' + longName(code) + (flag(code) ? "..." : "")
    }

    function hint(code) {
        return hintTable[code];
    }
}
